### ISSUE TITLE
Example in README does not produce the correct spectrum

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/MathieuFunctions.jl#3]
The example code produces values that look like this:
![figure_1](https://user-images.githubusercontent.com/416947/49667809-346e1480-fa2a-11e8-9e4e-e81917cf64f6.png)

This is likely related to issue #2

**Comment by wuxxxian** [comment]
In the example, the parameters (nu and q) passed into char\lambda function is in the wrong order. I reversed the order and it is giving the correct plot. 
a[i,:] = charλ(nu[i],q,k=1:nLevels);
Eng_half = charλ(-1,q,k=1:nLevels);
Eng_0 = charλ(0,q,k=1:nLevels);

**Comment by matthewware** [comment]
Right you are!  I'll have to do some digging to see where that error got introduced.  For now I might just update the doc.

**Comment by matthewware** [comment]
Fixed in latest master.
