### ISSUE TITLE
Characteristic values with negative q

### ISSUE THREAD

**Issue by kalvotom** [BBN-Q/MathieuFunctions.jl#5]
`charA(1/4)` works as expected, but when I try `charA(-1/4)` i get

```
julia> charA(-1/4)
ERROR: BoundsError: attempt to access 1-element UnitRange{Int64} at index [2]
Stacktrace:
 [1] getindex at ./range.jl:617 [inlined]
 [2] #charA#2(::UnitRange{Int64}, ::typeof(charA), ::Float64) at /home/kalvin/.julia/packages/MathieuFunctions/GaHrG/src/char-values.jl:63
 [3] charA(::Float64) at /home/kalvin/.julia/packages/MathieuFunctions/GaHrG/src/char-values.jl:50
 [4] top-level scope at REPL[19]:1
```

Verbose `charA(-1/4, k=0:4)` gives correct results, however.

**Comment by matthewware** [comment]
Hi kalvotom,

Yeas there is an issue with the way charA handles negative characteristic values.  I'll see if there's a quick way to fix this.

-Matt

**Comment by matthewware** [comment]
After a little digging I've confirmed this as an issue in 0.6 and > 1.0.  I'll have more info in a bit.

**Comment by matthewware** [comment]
Maybe give the master branch a try now.  I think the issue was a confusion with he 1-indexing in Julia.  All tests are now passing.

**Comment by matthewware** [comment]
I think this issue is solved now.  Let me know if you run into any other issues.
